language: go
go:
- '1.9'
install: true
script: git clone https://github.com/jmalloc/grit/ c1
deploy:
  provider: script
  script: git clone https://github.com/jmalloc/grit/ c2 2>&1
  skip_cleanup: true

